language: php

sudo: false

php:
    - 7.2
    - 7.3

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
    - composer self-update
    - composer install --prefer-dist --no-interaction

script: ./vendor/bin/phpunit -d memory_limit=1024M

matrix:
    fast_finish: true
